project_id = "zzefgdgfytzoyknpudub"

[functions.nse-stocks]
verify_jwt = false

[functions.predict-stock]
verify_jwt = false

[functions.research-prediction]
verify_jwt = false

[functions.market-assistant]
verify_jwt = false

[functions.stock-assistant]
verify_jwt = false
